on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: github/issue-labeler@v2
      with:
        repo-token: ${{ secrets.TOKEN }}
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
